# Site settings
title:          new bridge
description:    "The new bridge dev blog"
baseurl:        ""
url:            "https://blog.new-bridge.dev"

# Author
author:
  name:         Jochen
  url:          https://blog.new-bridge.dev
  email:        jochen.zehnder@gmail.com
  xing:         Jochen_Zehnder
  linkedin:     jochen-zehnder-5b750252
  slideshare:   JochenZehnder
  github:       elft3r
  twitter:      elft3r

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Makefile, README.md ]
